### ISSUE TITLE
SLIP-0023: Dead Link To BIP32-Ed25519 Paper

### ISSUE THREAD

**Issue by b-vennes** [satoshilabs/slips#1145]
The SLIP-0023 page contains a dead link to the _BIP32-Ed25519 Hierarchical Deterministic Keys over a Non-linear Keyspace_ paper which defines child-key derivations. I have found the paper and uploaded it on my Google Drive [here](https://drive.google.com/file/d/1HZ0RuclVHkh2Q_pgsgGht13o_GjlosHf), but there should probably be a more permanent spot for it somewhere official.

**Comment by andrewkozlik** [comment]
The most official link to the document is probably https://ieeexplore.ieee.org/document/7966967, but to access it, you need to pay. The best option would be to put the preprint right here on satoshilabs/slips Github, but I can't tell whether it's OK legally. @prusnak?

**Comment by prusnak** [comment]
> https://ieeexplore.ieee.org/document/7966967

I am fine with linking to this source

**Comment by andrewkozlik** [comment]
Fixed in https://github.com/satoshilabs/slips/commit/f2198fffbed862684eb1aa7a6b5eefc01d0277cb. I updated the links and added another link to Cardano's documentation https://github.com/input-output-hk/technical-docs/blob/main/cardano-components/cardano-wallet/doc/Wallet-Cryptography-and-Encoding.md#hierarchical-deterministic-wallets.
