### ISSUE TITLE
SLIP-0013: clarification for: user/signer and rationale for visual challenge

### ISSUE THREAD

**Issue by landabaso** [satoshilabs/slips#1259]
The challenge consists of a) URI + index, b) hidden random challenge to _user_ (a nonce?) and c) visual challenge

The _signer_ takes all this and signs.

I have 3 questions.

a)

Is the Challenge - Response section part of the SLIP or is it just a recommendation?

b)

Who/what is the _signer_?

The SLIP introduces 2 concepts: _user_ and _signer_.
Does _signer_ refer to a signing device/software?

The SLIP mentions that the random challenge is hidden to the _user_. However, it must be accessible to the _signer_.

So what does "hidden" mean? Does this simply mean that it is not displayed on the screen, but could be accessed by the _user_ anyway using dev tools in a browser-based login, for example? Why hide it?

c)

What is the rationale behind the need for an additional "visual" challenge? Isn't this an unnecessary burden for the user? Won't the user simply copy and paste it to an interface shown by the wallet?

Or are you assuming the _signer_ is also responsible for automatically taking the visual challenge and signing? Why show it then?

**Comment by bitcoin274** [comment]
thanks for the heads up its called corruption at its finest

**Comment by robledo6** [comment]
...

**Comment by robledo6** [comment]
...

**Comment by prusnak** [comment]
a) required, not recommended
b) user is an user, signer is a device/software; yes, hidden means it is not shown on a display of the signer; it does not have to stay as a secret, it can be shown, but user won't be able to decipher it anyway, since this is mostly a random byte sequence
c) user wants to know where they are logging into, so this information is shown on the display and becomes part of the hashed data which is then signed

**Comment by prusnak** [comment]
Btw, this standard was created before [FIDO2/WebAuthn](https://en.wikipedia.org/wiki/WebAuthn) came into existence. I would recommend using FIDO2 today for better interoperability with existing infrastructure (operating systems, browser, etc).
