### ISSUE TITLE
SLIP-0019: compliance with BIP322 latest version?

### ISSUE THREAD

**Issue by Sosthene00** [satoshilabs/slips#1496]
Hi, I was reading the SLIP-0019 and noticed that it explicitly refers to a previous version of BIP322 (before October 2020). 

I was interested to hear if this was because it is believed that the first BIP322 would fit the needs of this SLIP better or simply a factual statement meaning that the SLIP was never updated to account for BIP322 new version.

Afaict, it seems the SLIP could be updated like this and be compatible with latest BIP322:
* It's not necessary to have the `ScriptPubkey` in the `ScriptFooter`, since it will be provided as `message_challenge` and commited inside the txhash of the `to_spend` transaction.
* `sig_hash` is now `message_hash`, as specified in BIP322 (need to specify it is a BIP340 tagged hash)
* the `SignatureProof` is replaced by the `message_signature`

I think it covers both proof of non ownership AND proof of funds as you can add the UTXO you want to prove ownership of as inputs in the `to_sign` transaction.

**Comment by prusnak** [comment]
There was no reason to update SLIP-0019 to newer version of BIP322 since it seems the BIP is getting very little traction (AFAIK there is no wallet that supports it yet). On the other hand we've been using SLIP-0019 in production for more than two years now.

If BIP322 becomes widely used, we might consider updating SLIP-0019 to use the newer version.

**Comment by prusnak** [comment]
I will let @andrewkozlik decide whether he wants to add something more to the reasoning and/or to close the issue or to keep it open.

**Comment by louneskmt** [comment]
To give some more context, @Sosthene00 and I were looking into implementing SLIP-0019 and SLIP-0021 into the ColdCard firmware and HSM for fun (we are brainstorming about CoinJoins on hardware wallets), and that would require us to add BIP322 support as well, thus this issue. Not sure if we should implement this "outdated" (?) version of BIP322 instead of the latest version?

**Comment by andrewkozlik** [comment]
> To give some more context, @Sosthene00 and I were looking into implementing SLIP-0019 and SLIP-0021 into the ColdCard firmware and HSM for fun (we are brainstorming about CoinJoins on hardware wallets), and that would require us to add BIP322 support as well, thus this issue. Not sure if we should implement this "outdated" (?) version of BIP322 instead of the latest version?

If you want coinjoin support, then I recommend that you implement SLIP-19 in its current form, because it is already implemented in the Wasabi 2.0 coordinator and there are no plans to change it.

To avoid confusion, you don't have to call it BIP-322 support, just call the whole thing "SLIP-19 proof signature" or something like that. It's much simpler to implement than the current BIP-322. You just append the scriptSig and witness for the sighash. Any cryptocurrency wallet should already have functions to produce the scriptSig and witness in it's codebase.

**Comment by louneskmt** [comment]
All of this definitely makes sense, thanks!

**Comment by Sosthene00** [comment]
Yes, it makes sense, that's great you've been running it in production for so long I didn't know that. Thanks for the quick answer.
