### ISSUE TITLE
SLIP-0044: ETC?

### ISSUE THREAD

**Issue by mmazi** [satoshilabs/slips#25]
Any suggestion for the ETC coin type index? How about 160 (ETH is 60)?

**Comment by slush0** [comment]
Does ETC need separate type index? It's fork of ETH so ETC on existing accounts is naturally stored on ETH cointype. Introducing new cointype would make a lot of mess.

**Comment by mmazi** [comment]
Yes, all pre-fork accounts contained both ETH and ETC. But people now seem to consider ETH and ETC as separate coins (at least for trading) on separate chains and want to store ETH and ETC separately, on separate addresses. It seems most of the ETC/ETC that's currently being sent around has already been split onto different addresses. That's what the big exchanges do (eg. Poloniex, Kraken), and that's what Vitalik [suggests](https://blog.ethereum.org/2016/07/26/onward_from_the_hard_fork/):
> Users who are interested in taking any actions with their ETC, [...] are advised to use the splitter contract at address 0xaa1a6e3e6ef20068f7f8d8c835d2d22fd5116444 to move their ETC to a separate newly created account so as to avoid replay attacks

That exactly to mitigate the mess created by the two chains living side-by-side.

**Comment by slush0** [comment]
We'll accept pull request for new coin type if there'll be any ETC wallet using such type.

**Comment by btchip** [comment]
Preempting 61 for ETC. PR will come later today if ok (wallet : https://github.com/LedgerHQ/ledger-wallet-ethereum-chrome)

**Comment by dangershony** [comment]
That's very interesting how do we regard a chain split, ETC is now a coin on its own and I'd say should get it's own derivation path.
As cointype=61 is free we might as well save it for ETC (just in case)

**Comment by slush0** [comment]
Pull request still didn't come :-).

Anyway, I still think this will create a mess. From technical standpoint, there's no way how to distinguish between ETH and ETC, everything is the same, even genesis block is the same...

**Comment by mikeyb** [comment]
I thought this over quite a bit.  While I quite agree with @slush0, there is one consideration that may cause issue in the future.  Say I am handed the keys to an HD wallet, or take over some infrastructure using proper bip44 naming.  Say that the wallet is holding funds on the ETC chain but using Ether (0x8000003c - 60) as the coin type, this may lead to confusion and loss of funds if I incorrectly assume these are actually on the ETH chain.  While every good token holder would invest the time to research and understand the wallet and network these tokens are on, explicitly declaring ETH or ETC would be preferred, I assume.

I am working on a wallet right now with some others and we want to eventually make the wallet compatible on both networks, and it was agreed internally that having a specific coin type defined would be the cleanest solution long term.  Otherwise we are forced to implement a solution on the account level such as:

`m/0'/60'/0'/` for ETH
`m/0'/60'/1'/` for ETC

This just doesn't feel right as we are moving the coin type to the next level under account, which seems incorrect even though ETC and ETH are currently fundamentally the same.  Though this may change greatly in the future.  The networks in which they run on are completely different.

Further comparison, such as a coin cloned from an existing coin type listed in this slip would get its own allocation.  The only difference in this situation is the genesis block differs.  Technically it is the same exact coin, but obviously not running on the same network.

I made the [pull request](https://github.com/satoshilabs/slips/pull/31) but will let you all decide if it gets accepted or not.  I feel the clarity of defining a separate coin type would be the best option

**Comment by prusnak** [comment]
Closed because of #31
