### ISSUE TITLE
SLIP-0039: suggest to have 40 bits in the checksum

### ISSUE THREAD

**Issue by weijiguo** [satoshilabs/slips#429]
With RS(1024), the 30 bits of checksum can only automatically recover from 1-word error. However hand-writing is rather error prone and study shows an error rate as high as 0.9% per word (http://panko.shidler.hawaii.edu/HumanErr/Basic.htm). So it seems not uncommon to have 2-word errors in a SSS share. 

I am not sure if there are any other studies in this field. But I'd like to suggest that 40 bits used for checksum so that 2-word errors could be automatically recovered. 

(There are other aspects in BIP/SLIP-0039 that needs improvements in my opinion but I will bring that up in the mail list for a broader audience.)

**Comment by andrewkozlik** [comment]
We are not aiming for automatic error recovery, but rather for reliable error detection. Indeed, the proposal states:

> Implementations SHOULD NOT implement correction beyond potentially suggesting to the user where in the string an error might be found, without suggesting the correction to make.

The same recommendation is also made in BIP-0173 (Bech32), which uses a similar checksum scheme. There is a good reason for this. Automated error-correction changes invalid mnemonics into valid mnemonics. The problem is that if more than a few errors are made, then the auto-corrected mnemonic will be valid but wrong, i.e. different from the original. Use of such a mnemonic may cause funds to be lost irrecoverably. This is why the corrections should be made only by the user, who can inspect the hand-written mnemonic more closely and is therefore better qualified to decide where exactly the errors were made.

The current proposal for the RS1024 checksum is guaranteed to detect any three or fewer errors. If there are more than three errors, then RS1024 is almost guaranteed to detect them (with failure probability below 1 per billion). If there is only one error, then the software will be able to help by suggesting where that error might be found. So we believe that three checksum words are sufficient. However, I agree that if four checksum words were used as you propose, then the software would be able to help in locating the positions of errors even if two errors were made. Nevertheless we are not convinced that this is worth increasing the length of the mnemonics.

**Comment by weijiguo** [comment]
Well, “automatic error recovery” is not necessary a feature but only a capability - that some word errors could be inferred deterministically. Just to clarify. No disagreements here.

Meanwhile, could you elaborate more on 

> guaranteed to detect any three or fewer errors

What exactly do you mean by "three"? If you mean 3 of all mnemonic words entered are in error, I am afraid there is no guarantee to detect. In fact, in case of 2 mnemonic word error, the error polynomial could be written as E(x) = Y<sub>1</sub>x<sup>e<sub>1</sub></sup> + Y<sub>2</sub>x<sup>e<sub>2</sub></sup>. With 4 free coefficients (Y<sub>1</sub>, e<sub>1</sub>, Y<sub>2</sub>, e<sub>2</sub>), it is at least possible to make E(x) evaluate to 0 (modulo over the generating polynomial) in 3 given points (a, a<sup>2</sup>, a<sup>3</sup>, corresponding to a 3-word checksum).

**Comment by andrewkozlik** [comment]
I indeed mean that it is possible to detect if 3 of the mnemonic words entered are in error. This property follows from the fact that every Reed-Solomon code is an MDS code. Using 3 checksum words implies a minimum Hamming distance equal to 4, which means that it can detect 3 (or fewer) errors and can locate/correct 1 error, see https://en.wikipedia.org/wiki/Hamming_distance#Error_detection_and_error_correction.

in case of a 2 mnemonic word error, it is possible to make the error polynomial evaluate to 0 in at most 1 given non-zero point.
