### ISSUE TITLE
Can I set the value of curve seed

### ISSUE THREAD

**Issue by TiantaoZhu** [satoshilabs/slips#561]
For  example

Curve = "ed25519 seed" for the ed25519 

can I set "Ed25519 seed" for the ed25519 curve.

**Comment by anthony19114** [comment]
Per slip-0010:
The supported curves are

Curve = "Bitcoin seed" for the secp256k1 curve (this is compatible to BIP-0032).
Curve = "Nist256p1 seed" for the NIST P-256 curve.
Curve = "ed25519 seed" for the ed25519 curve.
For ed25519, the last step always succeeds since every 256-bit number (even 0) is a valid private key. 

I personally haven’t put much interest into it but I would assume more options are available depending on your application. Remember depending on the circumstances an E is much different than an e.

**Comment by prusnak** [comment]
No, don't do it.
