### ISSUE TITLE
Test for boundary conditions

### ISSUE THREAD

**Issue by iancoleman** [satoshilabs/slips#832]
I found that in ilap/slip39-js there was an [error when generating 16 groups](https://github.com/ilap/slip39-js/pull/12) of 1of1 member shares.

If the official test vectors  had a test for the boundaries this would have been avoided.

Would you consider adding some more tests to the official test vectors for the valid upper bounds?

Seems like there are hard boundaries at

G = 16
N<sub>i</sub> = 16

**Comment by tsusanka** [comment]
cc @andrewkozlik

**Comment by andrewkozlik** [comment]
I investigated the bug in ilap/slip39-js and as far as I can tell it had nothing to do with boundary conditions, but with incorrect modular arithmetic. Also I think the actual bug was not in the combining of shares, but in the generation of the shares and had to do with JavaScript not raising an exception when an array is accessed out of bounds. So the generated mnemonics would have probably been invalid, meaning that you can't make them into a valid test vector. Nevertheless I managed to generate a valid test vector which would have probably detected the bug in the modular arithmetic and added it in https://github.com/trezor/python-shamir-mnemonic/commit/87811d787fb679e48c435d36a644c0d786e8f83d.
